version: "3.8"
services:
  web:
    build:
      context: .
      args:
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./history:/app/my_project/app/history
      - ./db:/app/my_project/app/db